# Generated by Django 5.1.4 on 2025-01-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='Web Dasturlash', max_length=100),
            preserve_default=False,
        ),
    ]
